### ISSUE TITLE
Changing the starter/partner Pokemon will break the game

### ISSUE THREAD

**Issue by ebil-recycle-bin** [SunakazeKun/PMDe#3]
I was messing around by setting different Pokemon as the starter/partner Pokemon. I realized that putting Pokemon that aren't supposed to be starters or partners will cause the game to break after you make your rescue team with your partner.

It happens at the point where your partner will ask you to make and name your rescue team. After naming it, where you are supposed to pose toward the sky and the screen goes black, the game breaks. The sprites will fail to display (because they don't exist), and the game will be stuck there.

**Comment by SunakazeKun** [comment]
That's not a problem on the editor's side. The game tries to load sprites that don't exist.
