### ISSUE TITLE
Legendary Recruitment

### ISSUE THREAD

**Issue by shadowlucario50** [SunakazeKun/PMDe#4]
Messing around with the hacks, I noticed that I couldn't recruit any legendaries after either messing with their stats or messing with their dungeon. I attempted to recruit them with a Level 100 with a Friend Bow several times, but failed. I put on the Easy Recruit cheat to see if that would make a difference, but it didn't. However, buying the Friend Area into the shop (after putting it in there) made them recruitable. I never messed with the recruitment rate, and I don't know if it's the dungeon edit or the stats edit that broke it. I hope this glitch could be fixed in the future.

Thanks again for making such a great tool!

**Comment by SunakazeKun** [comment]
Will be investigated later.

**Comment by SunakazeKun** [comment]
Should be fixed in the next release. Thanks for pointing out!
