### ISSUE TITLE
Exclusivity for Pokémon/Dungeons [Suggestion]

### ISSUE THREAD

**Issue by shadowlucario50** [SunakazeKun/PMDe#6]
In the dungeons, certain Pokémon will not appear due to being locked until they are encountered. Using mission codes unlock these Pokémon, however I would like to have an option to have these Pokémon unlocked. Maybe a toggle to lock/unlock Pokémon until encountered.

There's also the dungeons only unlocked through codes, and I would like to have them unlocked once a requirement is met. I believe four different dungeons are unlocked when obtaining certain Friend Areas from missions, so maybe something similar to that.

Just throwing this idea into the idea box.

**Comment by SunakazeKun** [comment]
That's pretty interesting, never thought about this. However, this requires investigation.
EDIT: The data has been investigated. Editing the exclusive Pokémon will be available in v1.04b.
