### ISSUE TITLE
List of Dungeons that allow a Party Limit of 4

### ISSUE THREAD

**Issue by an8bitbatty** [SunakazeKun/PMDe#7]
**OK**... This may be the last question I **ever ask** if I can resolve this issue, I just edited a Clean, Vanilla copy of PMD: RRT, Changing everything to what I had, except for the Dungeon Data, (Because that's where things can go **very** wrong) I'd like to know, or perhaps a list of which Dungeons it's safe to edit the Party Limit of, (to 4) so that I don't break it like I usually do* ( '-_-)
I know I probably shouldn't edit **any** of the Unused or CORRUPTED Dungeons, but I wanted to know which ones that ARE Used & ARE NOT CORRUPTED, that I can **safely** edit without any worry of breaking the code of the game* It's such an important Quality of Life Improvement to the game that I just **HAVE** to have it back* It's just not the same not being able to go **anywhere** without the game nagging at me that I have "too many Pokémon in the Party at once", As bad if not **WORSE** than how annoying Navi or GLaDOS is!
Any Help would be **immensely** appreciated!
Also, as shadowlucario50 mentioned, "I'm using v1.03, and I can bring more Pokémon into the dungeon." what's the **most** Dungeons you can change (all of them that you can change) that allow you to bring 4 Pokémon into them at once? (without breaking the code of the game & locking you out of the 4-Pokémon-Limit*)

**Comment by SunakazeKun** [comment]
It is good as to how the editor handles that atm. I don't want to change that in the fear of fucking things up.
