### ISSUE TITLE
Typo: Crucnch

### ISSUE THREAD

**Issue by shadowlucario50** [SunakazeKun/PMDe#8]
When in the move editor, I noticed that Crunch was spelled like "Crucnch" on the move selection on the left hand side.

![error crucnch](https://user-images.githubusercontent.com/16264395/34082598-89521024-e31e-11e7-8270-813df0cb829a.PNG)

**Comment by SunakazeKun** [comment]
Thanks for telling me. The fix will be included in the next release.
